Resources:
  FrontendDNS:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: testapp.com.
      Name: www.testapp.com
      Type: A
      AliasTarget:
        DNSName: webapp-alb-1011688224.ap-southeast-1.elb.amazonaws.com
        HostedZoneId: Z1039636SR6N7OWT544Q
