AWSTemplateFormatVersion: '2010-09-09'
Description: VPC with public and private subnets for ECS webapp

Parameters:
  VpcCIDR:
    Type: String
    Default: 10.0.0.0/16

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: webapp-vpc

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: vpc-0fa57aca26d17b622
      InternetGatewayId: igw-05e48286bd6751a24

  PublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: vpc-0fa57aca26d17b622
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: ap-southeast-1a

  PublicSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: vpc-0fa57aca26d17b622
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: ap-southeast-1b
